name: system_status_macos
description: MacOS implementation of the system_status plugin
repository: https://github.com/mrasityilmaz/system_status_plugin/tree/main/system_status_macos
version: 1.0.1


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'
  

flutter:
  plugin:
    implements: system_status
    platforms:
      macos:
        pluginClass: SystemStatusPlugin
        dartPluginClass: SystemStatusMacOS


dependencies:
  flutter:
    sdk: flutter
  
  
  system_status_platform_interface: ^1.0.2


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1





