name: system_status_platform_interface
description: A common platform interface for the system_status plugin.
repository: https://github.com/mrasityilmaz/system_status_plugin/tree/main/system_status/system_status_platform_interface
version: 1.0.0
publish_to: 'system_status_platform_interface' 


environment:
  sdk: '>=3.5.0-218.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0



dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
