name: system_status
description: The system_status Plugin is a powerful and user-friendly tool designed to provide real-time statistics on RAM, battery, storage, and CPU usage for MacOS computers.
# repository: 
version: 1.0.0
#homepage: ""
publish_to: 'system_status' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: '>=3.5.0-218.0.dev <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  system_status_macos: 
    path : '../system_status_macos'
  system_status_platform_interface: 
    path : '../system_status_platform_interface'


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^3.0.1
  plugin_platform_interface: ^2.0.0
  mocktail: ^1.0.4



flutter:
  plugin:
    platforms: 
      macos:
        default_package: system_status_macos