name: system_status
description: The system_status Plugin is a powerful and user-friendly tool designed to provide real-time statistics on RAM, battery, storage, and CPU usage for MacOS computers.
repository: https://github.com/mrasityilmaz/system_status_plugin/tree/main/system_status
version: 1.0.0
homepage: "https://github.com/mrasityilmaz/system_status_plugin"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'
  


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  system_status_macos: ^1.0.0
  system_status_platform_interface: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^3.0.1
  plugin_platform_interface: ^2.0.0
  mocktail: ^1.0.4



flutter:
  plugin:
    platforms: 
      macos:
        default_package: system_status_macos